### ISSUE TITLE
分岐した後の逐次処理について

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/genomon_pipeline_cloud#1]
分岐した後に、その分岐の中で複数の処理が必要になる場合は、上記のmultiprocessingでまだ解決できていない。複数の処理の逐次処理をまとめる関数を別に作って、逐次処理をまとめて、そのまとめたものをmultiprocessingで投げるようにするか。

**Comment by friend1ws** [comment]
batch_engineクラスのexecute関数が、複数のmoduleを受け取ることができるようにして、これらを逐次的に実行する関数にすれば良いであろう。

**Comment by friend1ws** [comment]
```
def seq_execute_closure(self, general_param):
    def seq_execute(tasks):
        for task in tasks:
            subprocess.check_call(self.generate_commands(task, general_param))
    return seq_execute
```

のように、taskのクラスの配列を逐次実行する関数seq_executeのクロージャを用意して、batch_engineのインスタンス化を行い（インスタンス化した瞬間にseq_executeの関数がメンバとなる）、

```
p2 = multiprocessing.Process(target = batch_engine.seq_execute, args = ([fusionfusion_task, genomon_expression_task],))
p2.start()
p2.join()
```

という感じでいける。

**Comment by aokad** [comment]
対応済み
