### ISSUE TITLE
ファイルの確認について

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/genomon_pipeline_cloud#4]
sample_conf.pyではfastqやbamファイルの確認をしていたが、S3やGCSのファイルでもそれをするか？するとして、genomon_pipeline_cloud側でやるか？（awsub側でやるか？）

・genomon_pipeline_cloud側では最低限やった方が良いかなと思う。genomon_pipeline_cloud側でチェックをしないとすると、ファイルがないときに、awsub側でエラーになってしまい、綺麗なエラーハンドリングが難しくなってしまう。
・awsub側でもダブルチェック的にやっても良いと思う。時間がかかるかな？？
・とりあえずAWSではboto3あたりを使うのが良さそう。

**Comment by aokad** [comment]
ecsubにて対応済み
